apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-proc-grpc
spec:
  selector:
    matchLabels:
      app: grpc-ext-proc
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-ext-proc
    spec:
      containers:
        - name: grpc-ext-proc
          image: gcr.io/solo-test-236622/ext-proc-example-basic-sink:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: example-grpc-ext-proc
  labels:
    app: grpc-ext-proc
  annotations:
    gloo.solo.io/h2_service: "true"
spec:
  ports:
  - port:  18080
    protocol: TCP
  selector:
    app: grpc-ext-proc