global:
  extensions:
    extProc:
      grpcService:
        extProcServerRef:
          name: default-ext-proc-grpc-18080
          namespace: gloo-system
      filterStage:
        stage: AuthZStage
        predicate: After
      processingMode:
        requestHeaderMode: SEND
        responseHeaderMode: SEND
        requestBodyMode: BUFFERED
        responseBodyMode: BUFFERED
        requestTrailerMode: SEND
        responseTrailerMode: SEND